--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/10/2022 4:35:06 PM
-- Server version: 8.0.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE dms_v2;

--
-- Drop table `drive_files`
--
DROP TABLE IF EXISTS drive_files;

--
-- Drop table `user_configuration`
--
DROP TABLE IF EXISTS user_configuration;

--
-- Set default database
--
USE dms_v2;

--
-- Create table `user_configuration`
--
CREATE TABLE user_configuration (
  unique_id int DEFAULT NULL,
  cloud_type int DEFAULT NULL,
  refresh_token varchar(1000) DEFAULT NULL,
  is_connect tinyint(1) DEFAULT NULL,
  client_id varchar(1000) DEFAULT NULL,
  client_secret varchar(255) DEFAULT NULL,
  redirect_uri varchar(255) DEFAULT NULL,
  host_connection varchar(1000) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `drive_files`
--
CREATE TABLE drive_files (
  unique_id varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  cloud_type int DEFAULT NULL,
  file_name varchar(500) DEFAULT NULL,
  file_time_stamp datetime DEFAULT NULL,
  file_attribute varchar(500) DEFAULT NULL,
  file_extension varchar(255) DEFAULT NULL,
  file_content_type varchar(255) DEFAULT NULL,
  file_data longtext DEFAULT NULL,
  file_id varchar(255) DEFAULT NULL,
  webViewLink varchar(2000) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user_configuration
--
INSERT INTO user_configuration VALUES
(0, 1, '1//0gI7I0pbXgUNwCgYIARAAGBASNwF-L9IrMKJ_HqdJyjElz-3k8kYvK3cxqkqjBAvinLeYRuZCg7IvIykssjFKEHo5as_DHm8Uuks', 1, '423239451859-ipshm99p7b36ob42baivncq3o7ms1ol5.apps.googleusercontent.com', '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', 'https://dev.niftytrader.in', 'Server=dsigndpo-stagging.c3ie6pj2esgb.ap-south-1.rds.amazonaws.com;database=dms_v2;uid=dsigndpostagging;pwd=v6sejixH1Wqm;Port=3306;');

-- 
-- Dumping data for table drive_files
--
-- Table dms_v2.drive_files does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;